INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (17, 'd4T(30mg)+3TC(150mg)+LPV/r(200/50mg)', 'Lamivudine+Lopinavir/Ritonavir+Stavudine', 2, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (18, 'TDF/FTC(300/200mg)+LPV/r(200/50mg)', 'Emtricitabine+Tenofovir+Lopinavir/Ritonavir', 2, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (19, 'TDF(300mg)+3TC(150mg)+LPV/r(200/50mg)', 'Lamivudine+Lopinavir/Ritonavir+Tenofovir', 2, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (20, 'TDF(300mg)+3TC(150mg)+ATV/r(300/100mg)', 'Atazanavir/Ritonavir+Lamivudine+Tenofovir', 2, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (21, 'd4T/3TC/NVP(6/30/50mg)', 'Lamivudine+Nevirapine+Stavudine', 3, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (22, 'd4T/3TC/NVP(12/60/100mg)', 'Lamivudine+Nevirapine+Stavudine', 3, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (23, 'd4T(1mg/ml)+3TC(10mg/ml)+NVP(10mg/ml)', 'Lamivudine+Nevirapine+Stavudine', 3, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (24, 'd4T(20mg)+3TC(10mg/ml)+EFV(200mg)', 'Efavirenz+Lamivudine+Stavudine', 3, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (25, 'AZT(10mg/ml)+3TC(10mg/ml)+NVP(10mg/ml)', 'Lamivudine+Nevirapine+Zidovudine', 3, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (26, 'AZT(10mg/ml)+3TC(10mg/ml)+EFV(200mg)', 'Efavirenz+Lamivudine+Zidovudine', 3, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (27, 'd4T/3TC/EFV(6/30/200mg)', 'Efavirenz+Lamivudine+Stavudine', 3, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (28, 'd4T/3TC/EFV(12/60/200mg)', 'Efavirenz+Lamivudine+Stavudine', 3, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (29, 'AZT/3TC/NVP(60/30/50mg)', 'Lamivudine+Nevirapine+Zidovudine', 3, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (30, 'AZT/3TC/EFV(60/30/200mg)', 'Efavirenz+Lamivudine+Zidovudine', 3, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (31, 'ABC(60mg)+3TC(30mg)+NVP(50mg)', 'Abacavir+Lamivudine+Nevirapine', 3, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (32, 'ABC(60mg)+3TC(30mg)+EFV(200mg)', 'Abacavir+Efavirenz+Lamivudine', 3, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (33, 'ABC(20mg/ml)+DDI(10mg/ml)+LPV/r(80/20mg/ml)', 'Abacavir+Didanosine+Lopinavir/Ritonavir', 4, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (34, 'd4T(6mg)+3TC(30mg)+LPV/r(80/20mg/ml)', 'Lamivudine+Lopinavir/Ritonavir+Stavudine', 4, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (1, 'AZT(300mg)+3TC(150mg)+NVP(200mg)', 'Lamivudine+Nevirapine+Zidovudine', 1, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (2, 'AZT(300mg)+3TC(150mg)+EFV(600mg)', 'Efavirenz+Lamivudine+Zidovudine', 1, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (3, 'AZT(300mg)+3TC(150mg)+ABC(300mg)', 'Abacavir+Lamivudine+Zidovudine', 1, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (4, 'AZT(300mg)+3TC(150mg)+TDF(300mg)', 'Lamivudine+Tenofovir+Zidovudine', 1, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (5, 'ABC(300mg)+3TC(150mg)+NVP(200mg)', 'Abacavir+Lamivudine+Nevirapine', 1, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (6, 'ABC(300mg)+3TC(150mg)+EFV(600mg)', 'Abacavir+Efavirenz+Lamivudine', 1, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (7, 'd4T(30mg)+3TC(150mg)+NVP(200mg)', 'Lamivudine+Nevirapine+Stavudine', 1, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (8, 'd4T(30mg)+3TC(150mg)+EFV(600mg)', 'Efavirenz+Lamivudine+Stavudine', 1, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (9, 'TDF(300mg)+3TC(300mg)+NVP(200mg)', 'Lamivudine+Nevirapine+Tenofovir', 1, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (10, 'TDF(300mg)+3TC(300mg)+EFV(600mg)', 'Efavirenz+Lamivudine+Tenofovir', 1, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (11, 'TDF/FTC(300/200mg)+NVP(200mg)', 'Emtricitabine+Tenofovir+Nevirapine', 1, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (12, 'TDF/FTC(300/200mg)+EFV(600mg)', 'Efavirenz+Emtricitabine+Tenofovir', 1, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (13, 'AZT(300mg)+3TC(150mg)+LPV/r(200/50mg)', 'Lamivudine+Lopinavir/Ritonavir+Zidovudine', 2, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (14, 'AZT(300mg)+TDF/FTC(300/200mg)+LPV/r(200/50mg)', 'Emtricitabine+Lopinavir/Ritonavir+Tenofovir+Zidovudine', 2, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (15, 'ABC(300mg)+DDI(400mg)+IDV/r(400/50mg)', 'Abacavir+Didanosine+Indinavir/Ritonavir', 2, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (16, 'ABC(300mg)+DDI(400mg)+LPV/r(200/50mg)', 'Abacavir+Didanosine+Lopinavir/Ritonavir', 2, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (35, 'd4T(12mg)+3TC(60mg)+LPV/r(80/20mg/ml)', 'Lamivudine+Lopinavir/Ritonavir+Stavudine', 4, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (36, 'AZT(60mg)+3TC(30mg)+LPV/r(80/20mg/ml)', 'Lamivudine+Lopinavir/Ritonavir+Zidovudine', 4, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (37, 'ABC(60mg)+3TC(30mg)+LPV/r(80/20mg/ml)', 'Abacavir+Lamivudine+Lopinavir/Ritonavir', 4, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (38, 'AZT(300mg)', 'Zidovudine', 5, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (39, 'AZT(300mg)+3TC(150mg)', 'Lamivudine+Zidovudine', 5, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (40, 'AZT(300mg)+3TC(150mg)+EFV(600mg)', 'Efavirenz+Lamivudine+Zidovudine', 5, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (41, 'AZT(300mg)+3TC(150mg)+LPV/r(200/50mg)', 'Lamivudine+Lopinavir/Ritonavir+Zidovudine', 5, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (42, 'TDF/FTC(300mg/200mg)+NVP(200mg)', 'Emtricitabine+Tenofovir+Nevirapine', 5, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (43, 'TDF/FTC(300mg/200mg)+EFV(600mg)', 'Efavirenz+Emtricitabine+Tenofovir', 5, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (44, 'Cotrimoxazole 960mg', '', 8, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (45, 'Cotrimoxazole 480mg', '', 8, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (46, 'Cotrimoxazole 240mg/5ml', '', 8, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (47, 'Acyclovir 200mg', '', 9, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (48, 'Amoxycillin/Clavulanate 625mg', '', 9, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (49, 'Amoxycillin/Clavulanate 457mg/5ml', '', 9, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (50, 'Fluconazole 50mg', '', 9, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (51, 'Fluconazole 50mg/5ml', '', 9, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (52, 'Fluconazole 200mg', '', 9, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (53, 'Nystatin 100,000iu/ml', '', 9, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (54, 'Tinidazole 500mg', '', 9, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (55, 'Azithromycin 250mg', '', 12, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (56, 'Benzathine Penicillin', '', 12, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (57, 'Ceftriaxone 1g', '', 12, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (58, 'Ciprofloxacin 500mg', '', 12, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (59, 'Doxycycline 100mg', '', 12, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (60, 'Erythromycin 500mg', '', 12, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (61, 'Ofloxacin 200mg', '', 12, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (62, 'Spectinomycine 2g', '', 12, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (63, 'Tetracycline 500mg', '', 12, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (64, 'Amitryptiline 25mg', '', 13, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (65, 'Arthemeter/Lumefantrine 20/120mg', '', 13, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (66, 'Folic Acid 5mg', '', 13, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (67, 'Ferrous Sulphate 300mg', '', 13, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (68, 'Ferrous Gluconate 300mg', '', 13, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (69, 'Multivitamin', '', 13, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (70, 'Multivitamin Syrup', '', 13, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (71, 'Ibuprofen 200mg', '', 13, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (72, 'Loperamide 2mg', '', 13, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (73, 'Promethezine HCL 25mg', '', 13, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (74, 'Tramadol HCL 50mg', '', 13, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (75, 'Oral Dehydration Solution', '', 9, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (76, 'Fluoxetine 20mg', '', 9, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (77, 'Loratidine 10mg', '', 9, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (78, 'Metoclopramide 10mg', '', 9, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (79, 'Benzoic Acid/Salicylic Acid Ointment 6/3%', '', 9, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (80, 'Hydrocortisone 1%', '', 9, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (81, 'Chlorpheniramine 4mg', '', 9, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (82, 'Sulphadoxin/Pyrimethamine 500/25mg', '', 9, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (83, 'Ibuprofen 400mg', '', 9, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (84, 'Nystatin 500,000iu', '', 9, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (85, 'Zithromax 500mg', '', 9, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (86, 'Metronidazole 400mg', '', 9, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (87, 'Streptomycin 1g', '', 9, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (88, 'Ethambuthol/Isoniazid 400/150mg', '', 10, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (89, 'Rifampicin/Isoniazid 150/75mg', '', 10, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (90, 'Rifampicin/Isoniazid 60/30mg', '', 11, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (91, 'Rifampicin/Isoniazid/Pyrazinamide 60/30/150mg', '', 11, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (92, 'Rifampicin/Isoniazid/Pyrazinamide/Ethambuthol 150/75/400/275mg', '', 10, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (93, 'AZT(300mg)+TDF(300mg)+3TC(150mg)+ATV/r(300mg/100mg)', 'Atazanavir/Ritonavir+Lamivudine+Tenofovir+Zidovudine', 2, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (94, 'AZT(300mg)+TDF(300mg)+3TC(150mg)+LPV/r(200mg/50mg)', 'Lamivudine+Lopinavir/Ritonavir+Tenofovir+Zidovudine', 2, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (95, 'AZT(300mg)+3TC(150mg)+ATV/r(300mg/100mg)', 'Atazanavir/Ritonavir+Lamivudine+Zidovudine', 2, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (96, 'ABC(60mg)+3TC(30mg)+AZT(60mg)', 'Abacavir+Lamivudine+Zidovudine', 3, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (97, 'AZT/3TC(300/150mg)+NVP(200mg)', 'Zidovudine+Lamivudine+Nevarapin', 1, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (98, 'AZT/3TC/NVP(300/150/200mg)', 'Zidovudine+Lamivudine+Nevarapin', 1, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (99, 'AZT/3TC(300/150mg)+EFV(600mg)', 'Zidovudine+Lamivudine+Efavirenz', 1, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (100, 'AZT/3TC(300/150mg)+LPV/r(200/50mg)', 'Zidovudine+Lamivudine+Lopinavir/Ritonavir', 1, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (101, 'AZT/3TC(300/150mg)+EFV(200mg)', 'Zidovudine+Lamivudine+Efavirenz', 1, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (102, '3TC/FTC(300/300mg)+ATV/r(300/100mg)', 'Lamivudine+Emtricitabine+Atazanavir/Ritonavir', 2, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (103, '3TC/FTC(300/300mg)+EFV(600mg)', 'Lamivudine+Emtricitabine+Efavirenz', 2, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (104, '3TC/FTC(300/300mg)+LPV/r(200/50mg)', 'Lamivudine+Emtricitabine+Lopinavir/Ritonavir', 2, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (105, '3TC/FTC(300/300mg)+NVP(200mg)', 'Lamivudine+Emtricitabine+Nevarapin', 2, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (106, 'TDF(300mg)+3TC(300mg)+ATV/r(300/100mg)', 'Lamivudine+Tenofovir+Atazanavir/Ritonavir', 2, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (107, 'TDF(300mg)+3TC(300mg)+LPV/r(200/50mg)', 'Lamivudine+Tenofovir+Lopinavir/Ritonavir', 2, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (108, 'TDF/FTC(300mg/200mg)+ATV/r(300/100mg)', 'Atazanavir/Ritonavir+Emtricitabine+Tenofovir', 2, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (109, 'ABC(20mg/ml)+DDI(10mg/ml)+3TC(30mg)', 'Abacavir+Didanosine+Lamivudine', 4, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (110, 'DDI(10mg/ml)+3TC(30mg)+NVP(50mg)', 'Didanosine+Lamivudine+Nevirapine', 4, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (111, 'ABC(300mg)+3TC(150mg)+ATV/r(300/100mg)', 'Abacavir+Lamivudine+Atazanavir/Ritonavir', 2, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (112, 'ABC(300mg)+3TC(150mg)+LPV/r(200/50mg)', 'Abacavir+Lamivudine+Lopinavir/Ritonavir', 2, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (113, 'AZT(300mg)+TDF(300mg)+3TC(150mg)+ATV/r(300mg/100mg)', 'Lamivudine+Atazanavir/Ritonavir+Tenofovir+Zidovudine', 14, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (114, 'AZT(300mg)+TDF(300mg)+3TC(150mg)+LPV/r(200mg/50mg)', 'Lamivudine+Lopinavir/Ritonavir+Tenofovir+Zidovudine', 14, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (115, 'Isoniazid 300mg', '', 15, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (117, 'TDF(300mg)+FTC(200mg)+DTG(50mg)', 'Tenofovir+Emtricitabine+Dolutegravir', 1, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (118, 'ABC(20mg/ml)+3TC(300mg)+DTG(50mg)', 'Abacavir+Lamivudine+Dolutegravir', 3, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (119, 'ABC(20mg/ml)+FTC(200mg)+DTG(50mg)', 'Abacavir+Emtricitabine+Dolutegravir', 3, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (120, 'ABC(60mg)+3TC(30mg)+LPV/r(40/10mg)', 'Abacavir+Lamivudine+Lopinavir/Ritonavir', 3, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (121, 'AZT(60mg)+3TC(30mg)+LPV/r(40/10mg)', 'Zidovudine+Lamivudine+Lopinavir/Ritonavir', 3, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (124, 'ABC(60mg)+3TC(30mg)+DTG(50mg)', 'Abacavir+Lamivudine+Dolutegravir', 3, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (125, 'ABC(600mg)+3TC(300mg)+DTG(50mg)', 'Abacavir+Lamivudine+Dolutegravir', 1, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (126, 'ABC(600mg)+3TC(300mg)+LPV/r(200/50mg)+DTG(50mg)', 'Abacavir+Lamivudine+Lopinavir/Ritonavir+Dolutegravir', 14, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (127, 'TDF(300mg)+3TC(300mg)+LPV/r(200/50mg)+DTG(50mg)', 'Tenofovir+Lamivudine+Lopinavir/Ritonavir+Dolutegravir', 14, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (128, 'DTG(50mg)+LPV/r(200/50mg)', 'Dolutegravir+Lopinavir/Ritonavir', 14, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (129, 'Isoniazid 100mg', '', 15, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (116, 'TDF(300mg)+3TC(300mg)+DTG(50mg)', 'Tenofovir+Lamivudine+Dolutegravir', 1, true, 50);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (122, 'TDF(300mg)+3TC(30mg)+DTG(50mg)', 'Tenofovir+Lamivudine+Dolutegravir', 3, true, 50);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (200, 'Isoniazid 100mg', NULL, 15, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (201, 'TDF(300mg)+3TC(150mg)', 'Tenofovir+Lamivudine', 30, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (202, 'ABC(120mg)+3TC(60mg)+LPV/r(100mg/25mg)', 'Abacavir+Lamivudine+Lopinavir/Ritonavir', 3, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (203, 'ABC(120mg)+3TC(60mg)+LPV/r(40mg/10mg)', 'Abacavir+Lamivudine+Lopinavir/Ritonavir', 3, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (204, 'Isoniazid(300mg)/Pyridoxine(25mg)/Cotrimoxazole(960mg)', 'Isoniazid+Pyridoxine+Cotrimoxazole', 15, true, 1);
INSERT INTO hiv_regimen(id, description, composition, regimen_type_id, active, priority) VALUES (131, 'Isoniazid 100mg', NULL, 15, true, 1);

